/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kalkulatorasistensi;

import java.time.LocalDate;
import java.time.Period;

import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.scene.layout.VBox;
import javafx.scene.text.Font;
import javafx.scene.text.Text;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;


public class App extends Application {

    public static void main(String[] args) {
        Application.launch(args);
    }

    @Override
    public void start(Stage stage) throws Exception { // utk menampung scene2
        
        VBox vbox = new VBox();


        Label tittle = new Label("Kalkulator");
        tittle.setFont(Font.font("Arial", 20));
        vbox.getChildren().add(tittle); //memasukkan elemen2 yg d tas ke dlm vbox
        vbox.setSpacing(12); // jaraknya

        // Image gambar = new Image("/image/kalkulatorr.jpeg");
        

        Button startButton = new Button("Mulai");
        // startButton.getStyleClass().add("startButton");
        vbox.getChildren().addAll(startButton);
        vbox.setAlignment(Pos.CENTER); //utk mengatur posisi d tengah
        startButton.setOnAction(action -> { //utk mengatur apa action berikutnya pada saat tombol d tekan
            // Seluruh kode diantara {} disini akan dijalankan / dieksekusi ketika button sedang di click.
                tampilkanScen1(stage);
        });
        
        vbox.setStyle("-fx-background-color: #E6E6FA;");

        Scene scene = new Scene(vbox,320, 512); 
        
        stage.setScene(scene); // utk mengatur scene apa yg mau tampilkan
        stage.setTitle("Kalkulator Nakits");
        stage.show(); //utk menampilkan windownya
    }


    public void tampilkanScen1(Stage stage){
        VBox vbox = new VBox();
        Label judul = new Label ("Pilih Kalkulator");
        judul.setFont(Font.font("Arial",20));
        vbox.getChildren().add(judul);
        vbox.setSpacing(12.0);

        Button kalkulator1 = new Button("Kalkulator BMI");
        vbox.getChildren().add(kalkulator1);
        vbox.setAlignment(Pos.CENTER);
        vbox.setSpacing(12.0);
        kalkulator1.setOnAction(action -> {
            // Seluruh kode diantara {} disini akan dijalankan / dieksekusi ketika button sedang di click.
                kalkulatorBMI(stage);
        });

        Button kalkulator2 = new Button("Kalkulator Umur");
        vbox.getChildren().add(kalkulator2);
        vbox.setAlignment(Pos.CENTER);
        vbox.setSpacing(12.0);
        kalkulator2.setOnAction(action -> {
            // Seluruh kode diantara {} disini akan dijalankan / dieksekusi ketika button sedang di click.
                umur(stage);
        });

        vbox.setStyle("-fx-background-color: #E6E6FA;");

        Scene scene = new Scene(vbox, 320, 512);
        stage.setScene(scene);
        stage.show();
    }

    public void kalkulatorBMI(Stage stage){
        

        Label judul1 = new Label("KALKULATOR BMI");
        judul1.setFont(Font.font("Arial",20));

        TextField tfBerat = new TextField();
        tfBerat.setPromptText("Berat badan dalam kg");
        TextField tfTinggi = new TextField();
        tfTinggi.setPromptText("Tinggi badan dalam cm");
        Button buttonCalculate1 = new Button("Calculate");

        Label labelHasil1 = new Label();
        Button buttonBack1 = new Button("Kembali");
        buttonBack1.setOnAction(v->{
            tampilkanScen1(stage);
        });
        buttonCalculate1.setOnAction(v->{
            double tinggi= Double.parseDouble(tfTinggi.getText());
            tinggi=tinggi/100;
            double berat= Double.parseDouble(tfBerat.getText());
            double hasil = berat/(tinggi*tinggi);
            // labelHasil1.setText(String.format("%f", hasil));

            if (hasil >= 30) {
                labelHasil1.setText(String.format("%.2f, Obesitas II", hasil));
            } else if (hasil >= 25) {
                labelHasil1.setText(String.format("%.2f, Obesitas I", hasil));
            } else if (hasil >= 23) {
                labelHasil1.setText(String.format("%.2f, Kelebihan BB dan Beresiko Obesitas", hasil));
            } else if (hasil >= 18.5) {
                labelHasil1.setText(String.format("%.2f, Normal", hasil));
            } else {
                labelHasil1.setText(String.format("%.2f, Kekurangan BB", hasil));
            }
        });



        VBox vbox = new VBox(judul1, tfBerat,tfTinggi,buttonCalculate1, labelHasil1,buttonBack1); // utk memasukkan semua item2 ke dalam vbox
        vbox.setAlignment(Pos.CENTER);
        vbox.setSpacing(12.0);

        vbox.setStyle("-fx-background-color: #E6E6FA;");
        
        Scene scene = new Scene(vbox, 320, 512);
        stage.setScene(scene);
        stage.show();
    }

    public void umur(Stage stage){

        Label judul2 = new Label("KALKULATOR Umur");
        judul2.setFont(Font.font("Arial",20));

        TextField tfTanggal = new TextField();
        tfTanggal.setPromptText("YYYY-MM-DD");
        tfTanggal.requestFocus();


        Button buttoncalculate2 = new Button("Calculate");
        Label labelHasil2 = new Label("");
        Button buttonBack2 = new Button("Kembali");
        buttonBack2.setOnAction(v->{
            tampilkanScen1(stage);
        });
        buttoncalculate2.setOnAction(v->{
            // int tahun = Integer.parseInt(tfTahun.getText());
            // int umur = 2023 - tahun;
            // labelHasil2.setText(Integer.toString(umur));

            LocalDate dob = LocalDate.parse(tfTanggal.getText());
            LocalDate curDate = LocalDate.now();
            Period period = Period.between(dob, curDate);

            labelHasil2.setText(String.format("Umur Anda %d Tahun %d Bulan %d Hari", period.getYears(), period.getMonths(), period.getDays()));

        });


        VBox vbox = new VBox(judul2, tfTanggal, buttoncalculate2, labelHasil2, buttonBack2);
        vbox.setAlignment(Pos.CENTER);
        vbox.setSpacing(12.0);

        vbox.setStyle("-fx-background-color: #E6E6FA;");

        Scene scene = new Scene(vbox, 320, 512);
        stage.setScene(scene);
        stage.show();
    }
}
